Models/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Inmobiliaria_.Net_Core.Models
{
	public class LoginView
	{
		[DataType(DataType.EmailAddress)]
		public string Usuarios { get; set; }
		[DataType(DataType.Password)]
		public string Clave { get; set; }
	}
}

Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using mvc.Models;
using MVC.Models;


namespace MVC.Controllers
{
    public class ContratoController : Controller
    {
        private readonly ReposotorioInmueble repoInm ;
        private readonly RepositorioContrato repoCon;
        private readonly ReposotorioInquilino repoInq;
        public ContratoController()
        {
            repoInm = new ReposotorioInmueble();
            repoCon = new RepositorioContrato();
            repoInq = new ReposotorioInquilino();
        }
        // GET: Contrato
        [Authorize]
        public ActionResult Index()
        {
            var lista = repoCon.GetContratos();
        
            return View(lista);
        }
         [Authorize]
        public ActionResult VerContratos(int id)
        {
            var lista = repoCon.GetContratosPorInmueble(id);
            Console.WriteLine(lista.Count);
            return View(lista);
        }
        [Authorize]
        public ActionResult Listar(DateTime fechaDesde, DateTime fechaHasta)
        {
            if (fechaDesde == null && fechaHasta == null){
                fechaDesde = DateTime.Now;
                fechaHasta = DateTime.Now;
            }
            var lista = repoCon.GetContListarXfecha(fechaDesde,fechaHasta);
        
            return View(lista);
        }

        // POST: Contrato/Listar
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Buscar(DateTime desde, DateTime hasta)
        {
            var lista = repoCon.GetContListarXfecha(desde,hasta);
        
                 return RedirectToAction("Listar", new { lista });
        }

        // GET: Contrato/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
             var entidad = repoCon.GetContrato(id);
            return View(entidad);
        }

        // GET: Contrato/Create
        [Authorize]
         public ActionResult Create(int IdInmueble)
        {
            ViewBag.Inquilinos = repoInq.GetInquilinos();
            ViewBag.Inmuebles = repoInm.GetInmuebles();
            if (IdInmueble != null)
            {
				ViewData["IdInmueble"]= IdInmueble;
            }
            else
            {
				ViewData["IdInmueble"]=null;

            }
            ViewData["Error"] = "";
            return View();
        }

        // POST: Contrato/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Contrato contrato)
        {

            if (contrato.FecDesde >= contrato.FecHasta)
            {
                ViewBag.Inquilinos = repoInq.GetInquilinos();
                ViewBag.Inmuebles = repoInm.GetInmuebles();
                ViewData["Error"] = "La fecha de inicio debe ser menor que la fecha de fin.";
                return View();
            }
            else
            {

                if (!repoInm.EstaOcupado(contrato.IdInmueble, contrato.FecDesde, contrato.FecHasta, contrato.Id))
                {
                    ViewData["Error"] = "";
                    repoCon.Alta(contrato);
                    TempData["Id"] = contrato.Id;
                    return RedirectToAction(nameof(Index));
                    return View();
                }
                else
                {
                    ViewBag.Inquilinos = repoInq.GetInquilinos();
                    ViewBag.Inmuebles = repoInm.GetInmuebles();
                    ViewData["Error"] = "El inmueble esta ocupado en esas fechas";
                    return View();
                }
            }




            // Si hay errores en el modelo, volver al formulario para mostrar los errores.




        }

        // GET: Contrato/Edit/5
        [Authorize]
        public ActionResult Edit(int id, String a)
        {
            var entidad = repoCon.GetContrato(id);
           
            if(a!="Null"){
                ViewData["Titulo"]="Cancelar Contrato";
                 entidad.FecHasta = DateTime.Today;
            }
            else {
                ViewData["Titulo"]="Editar Contrato";
            }

            ViewData["Error"]=a;
            
			ViewBag.Inmuebles = repoInm.GetInmuebles();
            ViewBag.Inquilinos = repoInq.GetInquilinos();
			return View(entidad);
        }
        [Authorize]
        public ActionResult Renovar(int idInq, int idInm)
        {
            ViewData["Titulo"]="Renovar Contrato";
            ViewData["Error"]="";
            
                ViewBag.Inmuebles = repoInm.GetInmueble(idInm);
                ViewBag.Inquilinos = repoInq.GetInquilino(idInq);
                return View();
        }

        [Authorize]
        public ActionResult Cancelar(int id)
        {
            var contrato = repoCon.GetContrato(id);
            var inmueble = repoInm.GetInmueble(contrato.IdInmueble);

            var inicioContrato = contrato.FecDesde;
            var hoy = DateTime.Today;
            var diasTranscurridos = (int)(hoy - inicioContrato).TotalDays;

            var duracionContrato = (int)(contrato.FecHasta - inicioContrato).TotalDays;

            var mitadDuracion = duracionContrato / 2;
            var mesesAdicionales = diasTranscurridos < mitadDuracion ? 2 : 1;
            var a="";
            if (mesesAdicionales == 1)
            {
                a = "La multa a pagar es de " + 1 + " mes(es), un total de: $" + (inmueble.Precio * 1);
            }
            else
            {
                 a = "La multa a pagar es de " + 2 + " mes(es), un total de: $" + (inmueble.Precio * 2);
            }

            ViewBag.Inmuebles = repoInm.GetInmuebles();
            ViewBag.Inquilinos = repoInq.GetInquilinos();

            return RedirectToAction("Edit", new { id = contrato.Id , a });
        }
        // POST: Contrato/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, Contrato contrato)
        {

            bool inmuebleOcupado = repoInm.EstaOcupado(contrato.IdInmueble, contrato.FecDesde, contrato.FecHasta, contrato.Id);

            if (inmuebleOcupado)
            {
                ModelState.AddModelError("IdInmueble", "El inmueble se encuentra ocupado en esas fechas.");
                ViewBag.Inquilinos = repoInq.GetInquilinos();
                ViewBag.Inmuebles = repoInm.GetInmuebles();
                return View(contrato);
            }
            else {
                 contrato.Id = id;
                    repoCon.Modificar(contrato);
                    TempData["Mensaje"] = "Datos guardados correctamente";
                    return RedirectToAction(nameof(Index));
            }
            

            return View(contrato);
        }

        // GET: Contrato/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            var entidad = repoCon.GetContrato(id);
            return View(entidad);
        }

        // POST: Contrato/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                repoCon.Eliminar(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        
    }
}

Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using mvc.Models;
using MVC.Models;
namespace MVC.Controllers
{
    public class PagoController : Controller
    {    private readonly RepositorioContrato repoCon;
        private readonly RepositorioPago repoPago;
        public PagoController()
        {
            repoCon= new RepositorioContrato();
            repoPago = new RepositorioPago();
        }
        // GET: Pago
        [Authorize]
        public ActionResult Index()
        {
            var lista = repoPago.GetPagos(); 
        
            return View(lista);
        }
        [Authorize]
        public ActionResult VerPagos(int idInq)
        {
            var lista = repoPago.GetPagosPorContrato(idInq); 
        
            return View(lista);
        }

        // GET: Pago/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var entidad = repoPago.GetPago(id);
            return View(entidad);
        }

        // GET: Pago/Create
        [Authorize]
        public ActionResult Create()
        {
            try
            {
                
                ViewBag.Contratos=repoCon.GetContratos();
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        // GET: Pago/Create
        [Authorize]
        public ActionResult Crear(int idContrato)
        {

            try
            { 
                ViewBag.Contratos=repoCon.GetContratos();
                var entidad= repoCon.GetContrato(idContrato);
                
                return View();
            }
            catch (Exception ex)
            {
                throw ;
            }
        }

        // POST: Pago/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(Pago pago)
        {
            
                
					repoPago.Alta(pago);
					TempData["Id"] = pago.Id;
					return RedirectToAction(nameof(Index));
				
					
			
        }

        // GET: Pago/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var entidad = repoPago.GetPago(id);
			ViewBag.Contratos = repoCon.GetContratos();
			return View(entidad);
        }

        // POST: Pago/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, Pago pago)
        {
                pago.Id = id;
				repoPago.Modificar(pago);
				TempData["Mensaje"] = "Datos guardados correctamente";
				return RedirectToAction(nameof(Index));
        }

        // GET: Pago/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            var entidad = repoPago.GetPago(id);
            return View(entidad);
        }

        // POST: Pago/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
       [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                repoPago.Eliminar(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/Create.cshtml
@{
    ViewData["Title"] = "Persona ";
}

<div class="text-center">
    <h1 class="display-4">Nueva persona</h1>
</div>
<form asp-action="Create" method="post">
    <label for="Nombre">Nombre</label>
    <input type="text" id="Nombre" name="Nombre"><br>
    <label for="Apellido">Apellido</label>
    <input type="text" id="Apellido" name="Apellido"><br>
    <label for="Telefono">Telefono</label>
    <input type="text" id="Telefono" name="Telefono"><br>
    <label for="Mail">Mail</label>
    <input type="text" id="Mail" name="Mail"><br>
    <label for="Dni">Dni</label>
    <input type="number" id="Dni" name ="Dni"><br>
    <input type="submit" value="Guardar">
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header class="position-fixed top-0 w-100">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-sharp fa-solid fa-bars"></i>
    <span class="navbar-toggler-icon"></span>
</button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav me-auto mb-2 mb-md-0">
        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item" style="display: flex; align-items: center;">
                <i class="fa-solid fa-house"></i>
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"style="margin-left: 10px;">Home</a>
            </li>
            @if (User.IsInRole("Administrador"))
            {
                <li class="nav-item"style="display: flex; align-items: center;">
                    <i class="fa-solid fa-user"></i>
                    <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Index"style="margin-left: 5px;"> Usuarios</a>
                </li>
            }
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-solid fa-person"></i>
                <a class="nav-link" asp-area="" asp-controller="Inquilino" asp-action="Index"style="margin-left: 5px;"> Inquilino</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-solid fa-person"></i>
                <a class="nav-link" asp-area="" asp-controller="Propietario" asp-action="Index"style="margin-left: 5px;"> Propietario</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-solid fa-sign-hanging"></i>
                <a class="nav-link" asp-area="" asp-controller="Inmueble" asp-action="Index"style="margin-left: 5px;"> Inmueble</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-solid fa-file-contract"></i>
                <a class="nav-link" asp-area="" asp-controller="Contrato" asp-action="Index"style="margin-left: 5px;"> Contrato</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-sharp fa-solid fa-file-invoice-dollar"></i>
                <a class="nav-link" asp-area="" asp-controller="Pago" asp-action="Index"style="margin-left: 5px;"> Pago</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-sharp fa-regular fa-id-card"></i>
                <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Perfil"style="margin-left: 5px;"> Perfil</a>
            </li>
            <li class="nav-item"style="display: flex; align-items: center;">
                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Logout"style="margin-left: 5px;"> Salir</a>
            </li>
            
        }
        else
        {
            <li class="nav-item">
                <i class="fa-solid fa-right-to-bracket"></i>
                <a class="nav-link" asp-area="" asp-controller="Usuarios" asp-action="Login"style="margin-left: 5px;"> Iniciar Sesion</a>
            </li>
        }
    </ul>
    </div>
    
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Shared/_Login.cshtml
@model Inmobiliaria_.Net_Core.Models.LoginView

<h4>Acceso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Usuarios" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Usuarios" class="control-label"></label>
                <input asp-for="Usuarios" class="form-control" />
                <span asp-validation-for="Usuarios" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Entrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}